 <?php 

// $Id

/*
 * @file
 * General functions for debugging.
 */

/**
 * Implementation of hook_menu().
 */
function irodstools_menu() {
  // Administrative configuration menu item
  $items['admin/config/irods'] = array(
    'title' => 'iRODS Configuration',
    'description' =>
      t('Configuration page for editing iRODS server credentials.'),
    'position' => 'left',
    'weight' => -10,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer irods configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system')
  );

  // Custom path for marking projects as complete by URL verification
  $items["complete_project/%/verify/%"] = array(
    'title' => t("Verification for project completion via URL."),
    'page callback' => '_irodstools_complete_project',
    'page arguments' => array(1, 3),
    'access arguments' => array('submit project verification'),
    'type' => MENU_CALLBACK
  );


  return $items;
}

/**
 * Valid permissions for this module.
 * @return array of valid permissions for this module.
 */
function irodstools_perm() {
  return array('submit project verification');
}

/**
 * Function that marks a project as complete when the URL is called by a user.
 */
function _irodstools_complete_project($nid, $token) {
  // Only check if node found.
  if ($node = node_load($nid)) {
    
    /**
        TODO: Validate the token after finding out how it is stored in the
          database.

        See irods_mailer.module:55
     */

    // Update the node if the token is valid.
    if ($token) {

      $node->field_completed['und'][0]['value'] = 1;
      node_save($node);

      irods_mailer_notify_complete($node->nid);
      
      drupal_set_message(t("Successfully marked project $node->title as ".
        "complete."));
    }

    drupal_set_message(t("There was a verification error.  If you continute ".
      "to see this error, please contact BCF Support."), 'error', FALSE);
  }

  else {
    drupal_set_message(t("There was a problem loading the project.  If you ".
          "continue to see this error, please contact BCF Support."), 'error',
      FALSE);
  }

  global $base_path;

  header("Location: $base_path");
}

/**
 * Implementation of hook_block_info().
 */
function irodstools_block_info() {
  // Debugging block for showing node structure/contents.
  $blocks['irodstools'] = array(
     'info' => t('iRODS Monitor Debugging Block'),
    'cache' => DRUPAL_NO_CACHE
  );

  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function irodstools_block_view($delta = '0') {
  switch ($delta) {
    case 'irodstools':
      $block['subject'] = t("Debug Block");

      /**
        DEBUG BLOCK AREA
       */

      $content = "Testing...";
      $files = FALSE;
      $debug = TRUE;
      $content = irods_filetree_fetch($files, $debug);
      $block['content'] = $content;
    break;
  }

  // return $block;
}
